### ISSUE TITLE
Unset selectable

### ISSUE THREAD

**Issue by alexislozano** [alexislozano/neutrino#25]
As selectable is false by default, we don't need an `unset_selectable` function. Moreover, `set_selectable` should take no arguments, and only set selectable to true. All the other flags are already implemented like that, we should not change the API for one function.

Let me know if you want to do it @fabrixxm, I'll do it otherwise.

**Comment by fabrixxm** [comment]
My idea for Label was to have `selectable` true by default 

Il Lunedì 9 settembre 2019, alexislozano scrive:
> As selectable is false by default, we don't need an `unset_selectable` function. Moreover, `set_selectable` should take no arguments, and only set selectable to true. All the other flags are already implemented like that, we should not change the API for one function.
> 
> Let me know if you want to do it @fabrixxm, I'll do it otherwise.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/alexislozano/neutrino/issues/2

-- 
Inviato dal mio dispositivo Sailfish

**Comment by alexislozano** [comment]
Maybe we could then name the attribute "unselectable" and set it to false by default ? So this matches the API ?

**Comment by fabrixxm** [comment]
Yes. It is better :)


Il Lunedì 9 settembre 2019, alexislozano scrive:
> Maybe we could then name the attribute "unselectable" and set it to false by default ? So this matches the API ?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/alexislozano/neutrino/issues/25#issuecomment-52945353

-- 
Inviato dal mio dispositivo Sailfish

**Comment by alexislozano** [comment]
Okay, so I assign you to this task ;) Thanks !

**Comment by fabrixxm** [comment]
> Moreover, `set_selectable` should take no arguments, and only set selectable to true. All the other flags are already implemented like that, we should not change the API for one function.

`set_selectable()` is defined in `LabelState`, and take a parameter just like `set_stretched()`

the function defined in `Label` is `unset_selectable()` , with no args. `Label` is building its `LabelState` with `selectable` true, so is `unset_selectable()`

as we said I'll change `LabelState::selectable` to `LabelState::unselectable`, I'll update `LabelState` access functions and change `Label::unset_selectable()` to `Label::set_unselectable()`

Ok?

**Comment by alexislozano** [comment]
Exactly :D
