### ISSUE TITLE
Link progressbar, range, label and textinput in demo 

### ISSUE THREAD

**Issue by alexislozano** [alexislozano/neutrino#26]
I saw you did it in one of your branches @fabrixxm . Would it be possible for you to make a PR ? Let me know if you need help :)

**Comment by fabrixxm** [comment]
I'll wait for pr #27 to be merged in master.

**Comment by alexislozano** [comment]
no problem ;)

**Comment by fabrixxm** [comment]
PR #29

**Comment by alexislozano** [comment]
Done in #30
