### ISSUE TITLE
Examples are blank on macOS Mojave

### ISSUE THREAD

**Issue by AlesTsurko** [alexislozano/neutrino#4]
I tried these:

`hello_world`
`demo_default`
`image_viewer`

A window appears, but its content is blank.

Here a screenshot of `hello_world`:

![Screen Shot 2019-09-04 at 22 49 02](https://user-images.githubusercontent.com/8686568/64286493-4273a600-cf66-11e9-8545-4a3f82c5b9f7.png)

When I click inside of the window, a context menu with the field "Reload" appears (not sure whether it's a bug or a feature — should I open an issue for this too?). I do reload, but the window stays blank anyway.

![Screen Shot 2019-09-04 at 22 51 02](https://user-images.githubusercontent.com/8686568/64286603-85ce1480-cf66-11e9-9498-a868d07f0108.png)

**Comment by alexislozano** [comment]
Blank content is definitely a bug. For the Reload button, it should appear only when the debug attribute of window is set to true, which is not the case by default. So please fill another issue for this one :)

I don't have a Mac so I won't be able to test it, but could you try to deactivate the css ? For that replace the styles variable at the line 73 of lib.rs by an empty string.

**Comment by AlesTsurko** [comment]
> For that replace the styles variable at the line 73 of lib.rs by an empty string.

Unfortunately it doesn't work.

**Comment by alexislozano** [comment]
Hi ! I used an OSX VM and I could debug the issue. It is linked to the JS invoke function. I created an "osx" branch where I patched the bug, it now works in my VM. Could you try it on real hardware please ?

**Comment by AlesTsurko** [comment]
Yes, it works for me too.
