### ISSUE TITLE
State issues with login example on Windows

### ISSUE THREAD

**Issue by Songtronix** [alexislozano/neutrino#46]
The textboxes do not store the input correctly. If I write something and switch via Tab it works just fine. However if I switch via the mouse the textbox clears itself. Trying to log in doesn't work either.
Not sure if I misstype the password or the button is not working.

**Comment by alexislozano** [comment]
Hey ! It should be working now, it was an issue with the onchange event with IE :) Could you try the fix/login branch ? :D

**Comment by Songtronix** [comment]
Yes that fixed everything! Good job 👌

**Comment by alexislozano** [comment]
great !
