### ISSUE TITLE
Can reload from context menu in examples

### ISSUE THREAD

**Issue by AlesTsurko** [alexislozano/neutrino#5]
But according to [this](https://github.com/alexislozano/neutrino/issues/4#issuecomment-528097604) reply, the Reload button:

> should appear only when the debug attribute of window is set to true, which is not the case by default

**Comment by alexislozano** [comment]
This [issue](https://github.com/zserge/webview/issues/138) on the C lib provides a workaround. I am going to try it.

**Comment by alexislozano** [comment]
I pushed the fix in the "reload_menu" branch, it works in OSX VM and Linux. Could you try it on OSX ?
Normally, you should have the context menu when debug set to true (`window.set_debug()`) and no context menu when false (default)

**Comment by AlesTsurko** [comment]
I can't open the menu anymore.
