### ISSUE TITLE
[Question]: write html and attach events to rust from it.

### ISSUE THREAD

**Issue by rollback91** [alexislozano/neutrino#69]
Hi, first of all nice work! I really like your library!

I was wondering if there was a way to write html and add rust event listeners directly to it.

Thanks!

**Comment by alexislozano** [comment]
Hi ! Thanks a lot :) At first sight I would say to write your own widget. You can use Label as an simple example. Let me know if you need more details ;)

**Comment by rollback91** [comment]
Thanks for the quick reply! I'll let you know how it goes ;)
