### ISSUE TITLE
cargo test fails

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [alexislozano/neutrino#75]
A git clone, followed by `cargo test` gave me:

```
failures:

---- src/widgets/menubar.rs - widgets::menubar::MenuBar (line 89) stdout ----
error[E0061]: this function takes 3 parameters but 1 parameter was supplied
  --> src/widgets/menubar.rs:151:20
   |
64 |     let mut file = MenuItem::new("File");
   |                    ^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters

error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`.
Couldn't compile the test.
```

```
rustc --version
rustc 1.40.0 (73528e339 2019-12-16)
```

```
cargo --version
cargo 1.40.0 (bc8e4c8be 2019-11-22)
```

**Comment by alexislozano** [comment]
Hi ! Thanks for your message, it is resolved in the commit I just made (89c9caf).
It was an issue with the doc of MenuItem which I forgot to update.

**Comment by andrewdavidmackenzie** [comment]
Any plans to setup CI/CD testing (Travis, circle I)?

Want help with that?

**Comment by alexislozano** [comment]
Clearly, yes, would appreciate any help with that! Could you create à new issue about CI please ?

**Comment by andrewdavidmackenzie** [comment]
Will do. Travelling home and will be the weekend before I get quality time
on this.

In the issue you can let me know preferred CI platform, and the OS and rust
version matrix you would like to ensure works.

I use Travis and can do that easily with a .Travis.yml file and optional
for you to use it.

I want to learn CircleCI for projects of my own - so can use this as a
vehicle for that......then you can chose which you prefer.
