### ISSUE TITLE
Text color issue when desktop is in darkmode

### ISSUE THREAD

**Issue by fungos** [alexislozano/neutrino#81]
I use KDE/browser in dark mode and normally sites adapt accordingly, I wasn't expecting this to impact neutrino, but it does.. partially anyway. This is how it looks:

![image](https://user-images.githubusercontent.com/151544/74488887-8c57a500-4e91-11ea-8de0-85e7ea3b13de.png)

**Comment by alexislozano** [comment]
Thanks for opening the issue, I'll look at it
