### ISSUE TITLE
Am I blind or how do I build the `neutrino` app mentioned in the wiki examples

### ISSUE THREAD

**Issue by zzeroo** [alexislozano/neutrino#82]
All wiki examples mention a binary `neutrino`. Where do I find it. Or how can I build it?

> https://github.com/alexislozano/neutrino/wiki/Hello-World
> ```bash
> neutrino run --example hello_world
> ```

or 

> https://github.com/alexislozano/neutrino/wiki/Adding-data
> ```bash
> neutrino run --example add_data
> ```

**Comment by alexislozano** [comment]
Woops, it is `cargo run ...`

**Comment by zzeroo** [comment]
Thank you for this fast answer. I ask my next question strait here. Where do I find then the styling examples?

```bash
cargo run --example demo_default
cargo run --example demo_breeze
cargo run --example demo_adwaita
cargo run --example demo_osx
cargo run --example demo_fluent
error: no example target named `demo_default`
error: no example target named `demo_breeze`
error: no example target named `demo_adwaita`
error: no example target named `demo_osx`
error: no example target named `demo_fluent`
```

**Comment by alexislozano** [comment]
That is what I call writing the wiki first and then edit the code without editing back the wiki... So now the command is:
```
cargo run --example demo <theme>
```
Sp for instance to use the adwaita theme:
```
cargo run --example demo adwaita
```
If the theme name is not provided, it defaults to the default theme.
Going to change the wiki.
However, keep in mind I am not really working on neutrino anymore, if you want to use a GUI toolkit for production, maybe you should use another one. But if it is just for fun, enjoy ;)

**Comment by zzeroo** [comment]
Ok thanks that works for me. Thank you
